<!-- Image maps start here --!>
<map name="corner_map">
	<area href="http://guistuff.com" ALT="Images from guistuff.com" shape="rect" coords="1,1,65,15">
	<area href="http://afterstep.sf.net/" ALT="AfterStep Window Manager" shape="circle" coords="79,145,60">
</map>
<map name="title_map">
	<area href="ascompose.php" ALT="ASCompose" shape="rect" coords="39,102,291,115">
	<area href="http://prdownloads.sourceforge.net/afterstep/" ALT="libAfterImage (current version is 0.91, released on 12/30/01" shape="rect" coords="104,64,427,83">
	<area href="index.php" ALT="libAfterImage" shape="rect" coords="95,17,338,59">
</map>
<map name="menu_title_map">
	<area href="http://afterstep.sf.net/" ALT="AfterStep Window Manager" shape="circle" coords="79,25,60">
</map>

<map name="mi_intro_map"><area href="index.php" ALT="Introduction" shape="rect" coords="60,0,168,20"></map>
<map name="mi_features_map"><area href="features.php" ALT="Features" shape="rect" coords="60,0,168,20"></map>
<map name="mi_ss_map"><area href="screenshots.php" ALT="Screenshots" shape="rect" coords="60,0,168,20"></map>
	<map name="mi_ss_sub1_map"><area href="ss_sub1.php" ALT="Blending"           shape="rect" coords="60,0,168,20"></map>
	<map name="mi_ss_sub2_map"><area href="ss_sub2.php" ALT="Text and Gradients" shape="rect" coords="60,0,168,20"></map>
	<map name="mi_ss_sub3_map"><area href="ss_sub3.php" ALT="Image Quality"      shape="rect" coords="60,0,168,20"></map>
	<map name="mi_ss_sub4_map"><area href="ss_sub4.php" ALT="Quantization"       shape="rect" coords="60,0,168,20"></map>
<map name="mi_getcode_map"><area href="getcode.php" ALT="Get The Code" shape="rect" coords="60,0,168,20"></map>
<map name="mi_doc_map"><area href="documentation.php" ALT="Documentation" shape="rect" coords="60,0,168,20"></map>
	<map name="mi_apiref_map"><area href="http://www.afterstep.org/visualdoc.php?show=API/index" ALT="API Reference" shape="rect" coords="60,0,168,20"></map>
	<map name="mi_examples_map"><area href="examples.php" ALT="Examples" shape="rect" coords="60,0,168,20"></map>
	<map name="mi_ascompose_map"><area href="ascompose.php" ALT="ASCompose" shape="rect" coords="60,0,168,20"></map>
<map name="mi_support_map"><area href="support.php" ALT="Support" shape="rect" coords="60,0,168,20"></map>
<map name="mi_todo_map"><area href="todo.php" ALT="TODO" shape="rect" coords="60,0,168,20"></map>

<map name="bottombar_map"><area href="mailto:sashav@users.sourceforge.net" ALT="sashav@users.sourceforge.net" shape="rect" coords="210,1,295,19"></map>

